version: '3'

services:
  bienes-raices-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: bienes-raices-app
    container_name: bienes-raices-app
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:80"
    volumes:
      - ./LogsApache:/var/log/apache2
      - ./:/var/www/html
    networks:
      - localnet-containers
networks:
  localnet-containers:
    driver: bridge